site_name: JCOSMO Docs

nav:
  - Home: index.md
  - Theory Basics: basics.md
  - License: license-personal.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.extra

plugins:
  - search
  - bibtex:
      bib_file: "bib.bib"
